import React from 'react';

const AssemblyDisclaimer = () => (
    <div>
        <small className="header">Disclaimer: </small>
        <small>
            The foregoing leaves the possibility to have numbers that make sense even
            if no data is available for mismanaged - much as this distorts the
            rankings, still a number will be calculated, using an asterisk on the number
            or give it a different colour/pitch to warn it does not include reliable
            data on mismanaged waste. In result, most resource-efficient countries
            will show highest scores, and the less efficient ones lowest scores.
        </small>
        <br /><br />
        <small className="header">Sources:</small>
        <br />
        <ul className="small">
            <li>
                <small>
                    Acurio, G. et al. 1998. Diagnosis of Municipal Solid Waste Management
                    in Latin America and the Carribbean. Joint publication of the Inter-American
                    Development Bank and the Pan American Health Organization.
                </small>
            </li>
            <li>
                <small>
                    Department for International Development, 1999. CNTR 98 5698
                    Low Cost Solid Waste Incinerator: Demand Survey and Country Selection Report.
                </small>
            </li>
            <li>
                <small>
                    D-Waste, online waste atlas http://www.atlas.d-waste.com/
                </small>
            </li>
            <li>
                <small>
                    European Environnmental Agency, 2016. Municipal waste management
                    across European countries.
                </small>
            </li>
            <li>
                <small>
                    Eurostat, 2017. File:Municipal waste generated by country in selected years
                    (kg per capita).
                </small>
            </li>
            <li>
                <small>
                    The World Bank, 2012. What a Waste: A Global Review of Solid Waste Management.
                </small>
            </li>
            <li>
                <small>
                    The World Bank, 2017. GDP per capita, PPP (current international $).
                </small>
            </li>
        </ul>
    </div>
);

export default AssemblyDisclaimer;
